a =input("digita algo ")
print(f"o tipo primitivo desse valor e {type(a)}")
print(f"so tem espaço?{a.isspace()}")
print(f"tem numero?{a.isnumeric()}")
print(f"e alfabeto?{a.isalpha()}")
print(f'e alfanumerico?{a.isalnum()}')
print(f"e maiuscula?{a.isupper()}")
print(f"e minuscula?{a.islower()}")
print(f"estar capitalizada?{a.istitle()}")